name: driverent_manager
description: DriveRent Manager - offline self-drive car rental management app
publish_to: "none"
version: 2.0.4+11

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  path_provider: ^2.1.5
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  file_picker: ^10.3.3
  flutter_contacts: ^1.1.9+2
  pdf: ^3.11.1
  signature: ^5.5.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/DriveRent_Database.xlsx
    - assets/payment_qr.png
